# Generated by Django 5.2.1 on 2025-05-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_review_movie_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
