# Generated by Django 5.2.1 on 2025-06-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_view_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movies/movie_files'),
        ),
    ]
